import localFont from "next/font/local";
import "./globals.css";
import MovieProvider from "../context/MovieContext";
import ThemeProvider from "@/components/widgets/ThemeProvider";
import OnlineStatus from "@/components/widgets/OnlineStatus";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "MovieList",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <head />

      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable}`}
      >
        <ThemeProvider>
          <MovieProvider>
            <OnlineStatus>{children}</OnlineStatus>
          </MovieProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
